### ISSUE TITLE
Bəzi tapşırıqlar

### ISSUE THREAD

**Issue by EldanizAkbar** [aidashiraliyeva/PragmatechFoundationProject#3]
Zəhmət olmasa aşağıdakı tapşırıqları tez bir zamanda həll et.

- [ ] Lazımsız fayllları sil.(məs: example.docx, project.txt)
- [ ] Tasks qovluğunda yazdığın hər tapşırığı ayrı-ayrı qovluqlara yığ. Hər qovluğun adına - da tapşırığın verilən gününü yaz.
- [ ] Repo-dakı css qovluğu hansı html faylına aiddirsə onunla eynı qovluğa qoy

**Comment by aidashiraliyeva** [comment]
Düzəliş edildi
