### ISSUE TITLE
Section tag-indən istifadə

### ISSUE THREAD

**Issue by EldanizAkbar** [aidashiraliyeva/PragmatechFoundationProject#4]
https://github.com/aidashiraliyeva/PragmatechFoundationProject/blob/0ca38a1143001c5a899da208f91071ae50639c61/Project/index.html#L57

Zəhmət olmasa yazdığınız hər hissəni section tag-ində yazın. Hər bir section tag-inə class və ya id verərək həmin section-nın nə üçün yazıldığını izah edə bilərsiz.

**Comment by aidashiraliyeva** [comment]
section istifadə edildi
