### ISSUE TITLE
Düzəliş edilməli

### ISSUE THREAD

**Issue by EldanizAkbar** [aidashiraliyeva/PragmatechFoundationProject#7]
https://github.com/aidashiraliyeva/PragmatechFoundationProject/blob/ffd7eee88b4c8060a47d4ff5fbfe36388c7ccad3/Project/index.html#L161

Yazdığın bu hissədə görüntü problemi var. Zəhmət olmasa onu düzəlt

**Comment by aidashiraliyeva** [comment]
şəkli dəyişmişdim. Həll olub
