### ISSUE TITLE
Hover problemi

### ISSUE THREAD

**Issue by EldanizAkbar** [aidashiraliyeva/PragmatechFoundationProject#9]
https://github.com/aidashiraliyeva/PragmatechFoundationProject/blob/6ef8ea999a2ff87ef9a2ab8b4dd3545ca994016b/Project/html/index.html#L203

Bu hissədə **hover** işləmir. Zəhmət olmasa onu düzəlt

**Comment by aidashiraliyeva** [comment]
Həll olub
